"""init for migrations

Revision ID: c563b1dce259
Revises: 
Create Date: 2024-05-29 16:34:15.357970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c563b1dce259'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_member',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('chat_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('warn_count', sa.Integer(), nullable=False),
                    sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('0'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('new_chat_member',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('chat_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('user_answer', sa.Integer(), nullable=False),
                    sa.Column('question_message_id', sa.Integer(), nullable=False),
                    sa.Column('restriction_datetime', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_chat_member')
    op.drop_table('chat_member')
    # ### end Alembic commands ###
